services:
  - type: web
    name: skillswap-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://your-frontend-url.vercel.app